package com.gildaswise.notabook.core;

import java.util.Date;

import io.objectbox.annotation.Convert;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Relation;
import io.objectbox.annotation.Generated;
import io.objectbox.Box;
import io.objectbox.BoxStore;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.exception.DbDetachedException;
import io.objectbox.exception.DbException;
import io.objectbox.relation.ToOne;

/**
 * Created by Gildaswise on 17/05/2017.
 */

@Entity
public class ScheduleItem {

    @Id private Long id;
    @Convert(converter = Weekday.Converter.class, dbType = String.class) private Weekday weekday;
    @Relation private Notification notification;
    private Date startingAt;
    private Date endingAt;
    private int color;
    long notificationId;
    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;
    @Internal
    @Generated(1376660100)
    transient ToOne<Notification> notificationToOne = new ToOne<>(this, ScheduleItem_.notification);

    public ScheduleItem(Weekday weekday, Date startingAt, Date endingAt, int color) {
        this.weekday = weekday;
        this.startingAt = startingAt;
        this.endingAt = endingAt;
        this.color = color;
        this.notification = new Notification(startingAt);
    }

    @Generated(216485409)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public ScheduleItem(Long id, Weekday weekday, Date startingAt, Date endingAt, int color,
            long notificationId) {
        this.id = id;
        this.weekday = weekday;
        this.startingAt = startingAt;
        this.endingAt = endingAt;
        this.color = color;
        this.notificationId = notificationId;
    }

    @Generated(620347724)
    public ScheduleItem() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Weekday getWeekday() {
        return weekday;
    }

    public void setWeekday(Weekday weekday) {
        this.weekday = weekday;
    }

    public Date getStartingAt() {
        return startingAt;
    }

    public void setStartingAt(Date startingAt) {
        this.startingAt = startingAt;
    }

    public Date getEndingAt() {
        return endingAt;
    }

    public void setEndingAt(Date endingAt) {
        this.endingAt = endingAt;
    }

    public int getColor() {
        return color;
    }

    public void setColor(int color) {
        this.color = color;
    }

    public long getNotificationId() {
        return notificationId;
    }

    public void setNotificationId(long notificationId) {
        this.notificationId = notificationId;
    }

    /** To-one relationship, resolved on first access. */
    @Generated(1873712305)
    public Notification getNotification() {
        notification = notificationToOne.getTarget(this.notificationId);
        return notification;
    }

    /** Set the to-one relation including its ID property. */
    @Generated(1378506779)
    public void setNotification(Notification notification) {
        notificationToOne.setTarget(notification);
        this.notification = notification;
    }
}
